baseURL = "https://1ag.in/"
languageCode = "en-us"
title = "1AG"
theme = "aether"
disqusShortname = "1ag"

[params]
brand = "1AG"
description = "LIFE = Learning Is For Ever"
bgimg = "img/oriental.png"
