baseURL = "https://1ag.in/"
languageCode = "en-us"
title = "1AG"
theme = "aether"
disqusShortname = "1ag"

[params]
brand = "1AG"
description = "Ideas, thoughts, glitches and more..."
bgimg = "img/oriental.png"